#!/usr/bin/env bash
echo '\n' '\x00'
exit 1
#!/bin/sh

set -o nounset
set -o errexit
set -o pipefail

# https://wiki.gentoo.org/wiki/GCC_optimization
target="/etc/portage/cflags.conf"
cflags=$(resolve-march-native)
echo -e "# THIS FILE IS AUTOMATICALLY GENERATED BY ${0}\n" > "${target}"
echo "CFLAGS=\"${cflags}\"" >> "${target}"

source_line="source ${target}"
grep -E "^${source_line}$" /etc/portage/make.conf > /dev/null || { echo "${0}: ERROR, the line: \`${source_line}\` was not found in /etc/portage/make.conf" ; exit 1 ; }
